# global_frame: map
# robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 0.0
always_send_full_costmap: true
plugins:  
  - {name: static,       type: "costmap_2d::StaticLayer"}
  - {name: inflation,    type: "costmap_2d::InflationLayer"}

static:  
  map_topic: /map
  unknown_cost_value: -1
  lethal_cost_threshold: 50

# obstacle:  
#   observation_sources: base_scan
#   track_unknown_space: true
#   # base_scan: {data_type: LaserScan,    topic: /scan,    sensor_frame: laser,    clearing: true,    marking: true,    unknown_cost_value: -1}
#   base_scan: {data_type: PointCloud2,    topic: /lidar_segmented,    sensor_frame: laser,    clearing: true,    marking: true,    unknown_cost_value: -1}

inflation:
  cost_scaling_factor:  10  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.6 # max. distance from an obstacle at which costs are incurred for planning paths.
